// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf619BWY-M6iCJipvhOKxM3FKBhS8acos',
    appId: '1:293170647951:ios:6b2aa8f7108f22dec2b1fa',
    messagingSenderId: '293170647951',
    projectId: 'amenda-cuts',
    storageBucket: 'amenda-cuts.appspot.com',
    iosBundleId: 'com.example.amendaCuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf619BWY-M6iCJipvhOKxM3FKBhS8acos',
    appId: '1:293170647951:ios:6b2aa8f7108f22dec2b1fa',
    messagingSenderId: '293170647951',
    projectId: 'amenda-cuts',
    storageBucket: 'amenda-cuts.appspot.com',
    iosBundleId: 'com.example.amendaCuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR1v5_Pec8ITnxo8lPElqISX-ttTsOxx0',
    appId: '1:293170647951:web:d03e86a3ea065680c2b1fa',
    messagingSenderId: '293170647951',
    projectId: 'amenda-cuts',
    authDomain: 'amenda-cuts.firebaseapp.com',
    storageBucket: 'amenda-cuts.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR1v5_Pec8ITnxo8lPElqISX-ttTsOxx0',
    appId: '1:293170647951:web:d03e86a3ea065680c2b1fa',
    messagingSenderId: '293170647951',
    projectId: 'amenda-cuts',
    authDomain: 'amenda-cuts.firebaseapp.com',
    storageBucket: 'amenda-cuts.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnifoqK32Uh8Gyr3vUbNpIAmwOIQ7w_d8',
    appId: '1:293170647951:android:09979ebce768c28bc2b1fa',
    messagingSenderId: '293170647951',
    projectId: 'amenda-cuts',
    storageBucket: 'amenda-cuts.appspot.com',
  );

}